# Generated by Django 4.1.2 on 2022-12-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_circle_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
